import { EasyLab } from "../../../pages/Projects/EasyLab";
import { Ideal } from "../../../pages/Projects/Ideal";

export const projects = [
  {
    tags: [
      { id: 1, name: "React" },
      { id: 2, name: "JavaScript" },
      { id: 3, name: "Web Development" },
    ],
    name: "Easy Lab",
    description: "Title Description Project",
    component: EasyLab,
    id: "easylab",
    link: "/projects/easylab",
    dateProject: "07/2023",
    import: 2,
  },
  {
    tags: [
      { id: 1, name: "React" },
      { id: 2, name: "JavaScript" },
      { id: 3, name: "Web Development" },
    ],
    name: "?deal",
    description: "Title Description Project",
    component: Ideal,
    id: "ideal",
    link: "/projects/ideal",
    dateProject: "06/2023",
    import: 4,
  },
  {
    tags: [
      { id: 1, name: "React" },
      { id: 2, name: "JavaScript" },
      { id: 3, name: "Web Development" },
    ],
    name: "Atena",
    description: "Title Description Project",
    component: Ideal,
    id: "atena",
    link: "/projects/atena",
    dateProject: "06/2023",
    import: 1,
  },
  {
    tags: [
      { id: 1, name: "React" },
      { id: 2, name: "JavaScript" },
      { id: 3, name: "Web Development" },
    ],
    name: "Idy OS Program",
    description: "Title Description Project",
    component: Ideal,
    id: "idyProgram",
    link: "/projects/idyprogram",
    dateProject: "06/2023",
    import: 5,
  },
  {
    tags: [
      { id: 1, name: "React" },
      { id: 2, name: "JavaScript" },
      { id: 3, name: "Web Development" },
    ],
    name: "Coffee House",
    description: "Title Description Project",
    component: Ideal,
    id: "coffeeHouse",
    link: "/projects/coffeehouse",
    dateProject: "06/2023",
    import: 5,
  },
  {
    tags: [
      { id: 1, name: "React" },
      { id: 2, name: "JavaScript" },
      { id: 3, name: "Web Development" },
    ],
    name: "Ignite Feed",
    description: "Title Description Project",
    component: Ideal,
    id: "igniteFeed",
    link: "/projects/ignitefeed",
    dateProject: "06/2023",
    import: 5,
  },
  {
    tags: [
      { id: 1, name: "React" },
      { id: 2, name: "JavaScript" },
      { id: 3, name: "Web Development" },
    ],
    name: "Vision Gallery",
    description: "Title Description Project",
    component: Ideal,
    id: "visionGallery",
    link: "/projects/visiongallery",
    dateProject: "06/2023",
    import: 5,
  },
  {
    tags: [
      { id: 1, name: "React" },
      { id: 2, name: "JavaScript" },
      { id: 3, name: "Web Development" },
    ],
    name: "Coffee Delivery",
    description: "Title Description Project",
    component: Ideal,
    id: "coffeeDelivery",
    link: "/projects/coffee-delivery",
    dateProject: "06/2023",
    import: 5,
  },
];
